### ISSUE TITLE
Question: how can i get this as an extention

### ISSUE THREAD

**Issue by Terence-1** [bsiever/pxt-morsedecoder#1]
I am doing a morse code project where i can message my friend with it and this seems like a more suitable extention compared to your clicks one, how do i get it?

**Comment by Terence-1** [comment]
nvm i found out

**Comment by bsiever** [comment]
@Terence-1 I just created this today and it's not quite finished yet...but yes, it can be used as an extension.  I expect to be mostly done with it in another day or two.

**Comment by Terence-1** [comment]
@bsiever Thanks
